# 220968280 - Anirudh Swaminathan - DSE A2

## exercise1-week11 collaborative filtering using movielens dataset

In [1]:
import pandas as pd
import matplotlib as plt
import seaborn as sn
from sklearn.metrics import pairwise_distances 
from scipy.spatial.distance import cosine, correlation 
import numpy as np 
%matplotlib inline

In [2]:
ratings = pd.read_csv("C:/Users/s_ani/Documents/da/ratings.csv")
ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

### 2. Read the “ratings.csv” file and create a pivot table with index=‘userId’, columns=‘movieId’, values = “rating.

In [3]:
pivot_table = ratings.pivot(index='userId', columns='movieId', values='rating')
pivot_table.fillna(0, inplace=True)
pivot_table

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 3. sklearn.metrics.pairwise_distances can be used to compute distance between all pairs of users. pairwise_distances() takes a metric parameter for what distance measure to use.

In [4]:
distances = pairwise_distances(pivot_table.values, metric='cosine')
distances

array([[0.        , 0.97271713, 0.94027974, ..., 0.70890263, 0.90642807,
        0.85467919],
       [0.97271713, 0.        , 1.        , ..., 0.95378905, 0.9724346 ,
        0.89757325],
       [0.94027974, 1.        , 0.        , ..., 0.97887154, 1.        ,
        0.96788125],
       ...,
       [0.70890263, 0.95378905, 0.97887154, ..., 0.        , 0.87800729,
        0.67794514],
       [0.90642807, 0.9724346 , 1.        , ..., 0.87800729, 0.        ,
        0.94677454],
       [0.85467919, 0.89757325, 0.96788125, ..., 0.67794514, 0.94677454,
        0.        ]])

### 6. Find the 5 most similar user for user with user Id 10.

In [5]:
user_id = 10
similar_users = pd.Series(distances[user_id-1]).sort_values(ascending=True)[1:6].index + 1
print(f'most similar users are to user 10 are: {similar_users.to_list()}')

most similar users are to user 10 are: [159, 143, 563, 177, 189]

In [6]:
movies = pd.read_csv("C:/Users/s_ani/Documents/da/movies.csv")
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

### 7. Use the “movies” dataset to find out the names of movies, user 2 and user 338 have watched in common and how they have rated each one of them.

In [7]:
merged_df=pd.merge(ratings, movies, on='movieId')

In [8]:
user2=merged_df[merged_df['userId'] == 2]
user2

,userId,movieId,rating,timestamp,title,genres
2267,2,333,4.0,1445715029,Tommy Boy (1995),Comedy
15657,2,3578,4.0,1445714885,Gladiator (2000),Action|Adventure|Drama
16296,2,318,3.0,1445714835,"Shawshank Redemption, The (1994)",Crime|Drama
16613,2,1704,4.5,1445715228,Good Will Hunting (1997),Drama|Romance
16754,2,6874,4.0,1445714952,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller
16885,2,8798,3.5,1445714960,Collateral (2004),Action|Crime|Drama|Thriller
16929,2,46970,4.0,1445715013,Talladega Nights: The Ballad of Ricky Bobby (2...,Action|Comedy
16957,2,48516,4.0,1445715064,"Departed, The (2006)",Crime|Drama|Thriller
17064,2,58559,4.5,1445715141,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
17213,2,60756,5.0,1445714980,Step Brothers (2008),Comedy
17241,2,68157,4.5,1445715154,Inglourious Basterds (2009),Action|Drama|War
17329,2,71535,3.0,1445714974,Zombieland (2009),Action|Comedy|Horror
17382,2,74458,4.0,1445714926,Shutter Island (2010),Drama|Mystery|Thriller
17449,2,77455,3.0,1445714941,Exit Through the Gift Shop (2010),Comedy|Documentary
17462,2,79132,4.0,1445714841,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
17605,2,80489,4.5,1445715340,"Town, The (2010)",Crime|Drama|Thriller
17627,2,80906,5.0,1445715172,Inside Job (2010),Documentary
17639,2,86345,4.0,1445715166,Louis C.K.: Hilarious (2010),Comedy
17648,2,89774,5.0,1445715189,Warrior (2011),Drama
17659,2,91529,3.5,1445714891,"Dark Knight Rises, The (2012)",Action|Adventure|Crime|IMAX
17735,2,91658,2.5,1445714938,"Girl with the Dragon Tattoo, The (2011)",Drama|Thriller
17777,2,99114,3.5,1445714874,Django Unchained (2012),Action|Drama|Western
17848,2,106782,5.0,1445714966,"Wolf of Wall Street, The (2013)",Comedy|Crime|Drama
17902,2,109487,3.0,1445715145,Interstellar (2014),Sci-Fi|IMAX
17975,2,112552,4.0,1445714882,Whiplash (2014),Drama
18013,2,114060,2.0,1445715276,The Drop (2014),Crime|Drama|Thriller
18016,2,115713,3.5,1445714854,Ex Machina (2015),Drama|Sci-Fi|Thriller
18044,2,122882,5.0,1445715272,Mad Max: Fury Road (2015),Action|Adventure|Sci-Fi|Thriller
18091,2,131724,5.0,1445714851,The Jinx: The Life and Deaths of Robert Durst ...,Documentary

In [9]:
user338=merged_df[merged_df.userId==338]
user338

,userId,movieId,rating,timestamp,title,genres
692,338,50,4.5,1530148314,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
1997,338,296,4.5,1530148321,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
3684,338,527,5.0,1530148425,Schindler's List (1993),Drama|War
4462,338,593,4.0,1530148318,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller
14435,338,2959,4.5,1530148426,Fight Club (1999),Action|Crime|Drama|Thriller
16473,338,318,5.0,1530148309,"Shawshank Redemption, The (1994)",Crime|Drama
16831,338,6874,4.5,1530148453,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller
21265,338,1203,5.0,1530148436,12 Angry Men (1957),Drama
36403,338,5349,3.0,1530148456,Spider-Man (2002),Action|Adventure|Sci-Fi|Thriller
36617,338,5445,2.0,1530148457,Minority Report (2002),Action|Crime|Mystery|Sci-Fi|Thriller
37134,338,5952,3.0,1530148450,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
38040,338,7153,2.5,1530148449,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
41633,338,30749,3.5,1530148355,Hotel Rwanda (2004),Drama|War
45469,338,858,4.5,1530148305,"Godfather, The (1972)",Crime|Drama
50211,338,27773,4.0,1530148366,Old Boy (2003),Mystery|Thriller
50593,338,1221,5.0,1530148346,"Godfather: Part II, The (1974)",Crime|Drama
54189,338,8784,4.0,1530148361,Garden State (2004),Comedy|Drama|Romance
54350,338,30793,2.5,1530148341,Charlie and the Chocolate Factory (2005),Adventure|Children|Comedy|Fantasy|IMAX
54523,338,34405,3.5,1530148351,Serenity (2005),Action|Adventure|Sci-Fi
57570,338,177593,5.0,1530148460,"Three Billboards Outside Ebbing, Missouri (2017)",Crime|Drama
70952,338,122912,1.5,1530148370,Avengers: Infinity War - Part I (2018),Action|Adventure|Sci-Fi
70967,338,122916,1.0,1530148466,Thor: Ragnarok (2017),Action|Adventure|Sci-Fi
70986,338,176371,1.0,1530148373,Blade Runner 2049 (2017),Sci-Fi
70997,338,187541,1.0,1530148375,Incredibles 2 (2018),Action|Adventure|Animation|Children
71007,338,187593,1.0,1530148465,Deadpool 2 (2018),Action|Comedy|Sci-Fi
79008,338,170705,2.5,1530148439,Band of Brothers (2001),Action|Drama|War
81496,338,174053,5.0,1530148430,Black Mirror: White Christmas (2014),Drama|Horror|Mystery|Sci-Fi|Thriller
86994,338,177765,2.5,1530148369,Coco (2017),Adventure|Animation|Children
93463,338,185029,1.0,1530148471,A Quiet Place (2018),Drama|Horror|Thriller
93578,338,183897,1.5,1530148463,Isle of Dogs (2018),Animation|Comedy
95124,338,175569,1.5,1530148469,Wind River (2017),Action|Crime|Mystery|Thriller
97111,338,189043,2.5,1530148447,Boundaries (2018),Comedy|Drama
97112,338,189111,3.0,1530148343,Spiral (2018),Documentary
97113,338,190207,1.5,1530148481,Tilt (2011),Drama|Romance
97114,338,190209,4.0,1530148487,Jeff Ross Roasts the Border (2017),Comedy
97115,338,190213,1.0,1530148478,John From (2015),Drama
97116,338,190215,1.5,1530148477,Liquid Truth (2017),Drama
97117,338,190219,1.0,1530148473,Bunny (1998),Animation
97118,338,190221,1.0,1530148473,Hommage à Zgougou (et salut à Sabine Mamou) (2...,Documentary

In [10]:
common_movies = pd.merge(user2, user338, on='movieId')
common_movies

,userId_x,movieId,rating_x,timestamp_x,title_x,genres_x,userId_y,rating_y,timestamp_y,title_y,genres_y
0,2,318,3.0,1445714835,"Shawshank Redemption, The (1994)",Crime|Drama,338,5.0,1530148309,"Shawshank Redemption, The (1994)",Crime|Drama
1,2,6874,4.0,1445714952,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller,338,4.5,1530148453,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller

### 8. Use the movies dataset to find out the common movie names between user 2 and user 338 with least rating of 4.0

In [11]:
common_movies_high_rating = common_movies[(common_movies['rating_x'] >= 4.0) & (common_movies['rating_y'] >= 4.0)]
common_movies_high_rating

,userId_x,movieId,rating_x,timestamp_x,title_x,genres_x,userId_y,rating_y,timestamp_y,title_y,genres_y
1,2,6874,4.0,1445714952,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller,338,4.5,1530148453,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller

### 9. Create a pivot table for representing the similarity among movies using correlation

In [12]:
pivot_table = merged_df.pivot_table(index='userId', columns='title', values='rating')
correlation_table = pivot_table.corr(method='pearson')
correlation_table

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),NaN,NaN,NaN,NaN,NaN,NaN,-0.067522,NaN,-0.388883,1.000000,...,NaN,NaN,NaN,NaN,NaN,1.000000,0.762493,NaN,-0.337963,NaN
xXx (2002),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.831858,NaN,...,NaN,-0.595769,-1.0,NaN,NaN,0.762493,1.000000,0.94388,0.500000,NaN
xXx: State of the Union (2005),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,NaN,-0.755929,NaN,NaN,NaN,NaN,0.943880,1.00000,NaN,NaN
¡Three Amigos! (1986),NaN,NaN,NaN,NaN,NaN,NaN,-0.002732,NaN,0.572078,0.622543,...,NaN,NaN,NaN,NaN,NaN,-0.337963,0.500000,NaN,1.000000,NaN
À nous la liberté (Freedom for Us) (1931),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 10. Find the top 5 movies which are similar to the movie “Godfather”.

In [13]:
godfather=correlation_table["Godfather, The (1972)"]
godfather.sort_values(ascending=False).head(5)

title
Circus, The (1928)     1.0
Victoria (2015)        1.0
Why We Fight (2005)    1.0
Blue Car (2002)        1.0
I, Tonya (2017)        1.0
Name: Godfather, The (1972), dtype: float64